/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.dockercompose.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.dockercompose.ide.contentassist.antlr.internal.InternalDockerComposeParser;
import org.xtext.example.dockercompose.services.DockerComposeGrammarAccess;

public class DockerComposeParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(DockerComposeGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, DockerComposeGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getServiceAccess().getAlternatives_3_0(), "rule__Service__Alternatives_3_0");
			builder.put(grammarAccess.getServiceAccess().getAlternatives_3_8_1(), "rule__Service__Alternatives_3_8_1");
			builder.put(grammarAccess.getServiceAccess().getAlternatives_3_10_1(), "rule__Service__Alternatives_3_10_1");
			builder.put(grammarAccess.getServiceAccess().getAlternatives_3_11_1(), "rule__Service__Alternatives_3_11_1");
			builder.put(grammarAccess.getServiceAccess().getAlternatives_3_12_1(), "rule__Service__Alternatives_3_12_1");
			builder.put(grammarAccess.getServiceAccess().getAlternatives_3_14_1(), "rule__Service__Alternatives_3_14_1");
			builder.put(grammarAccess.getImageAccess().getAlternatives(), "rule__Image__Alternatives");
			builder.put(grammarAccess.getNetworkConnectorAccess().getAlternatives_1(), "rule__NetworkConnector__Alternatives_1");
			builder.put(grammarAccess.getNetworkAccess().getAlternatives_3(), "rule__Network__Alternatives_3");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getRestartPolicyAccess().getAlternatives(), "rule__RestartPolicy__Alternatives");
			builder.put(grammarAccess.getAccessModeAccess().getAlternatives(), "rule__AccessMode__Alternatives");
			builder.put(grammarAccess.getMountTypeAccess().getAlternatives(), "rule__MountType__Alternatives");
			builder.put(grammarAccess.getPropagationTypeAccess().getAlternatives(), "rule__PropagationType__Alternatives");
			builder.put(grammarAccess.getConditionAccess().getAlternatives(), "rule__Condition__Alternatives");
			builder.put(grammarAccess.getDockerComposeAccess().getGroup_0(), "rule__DockerCompose__Group_0__0");
			builder.put(grammarAccess.getDockerComposeAccess().getGroup_1(), "rule__DockerCompose__Group_1__0");
			builder.put(grammarAccess.getDockerComposeAccess().getGroup_2(), "rule__DockerCompose__Group_2__0");
			builder.put(grammarAccess.getDockerComposeAccess().getGroup_3(), "rule__DockerCompose__Group_3__0");
			builder.put(grammarAccess.getDockerComposeAccess().getGroup_4(), "rule__DockerCompose__Group_4__0");
			builder.put(grammarAccess.getDockerComposeAccess().getGroup_5(), "rule__DockerCompose__Group_5__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup(), "rule__EDouble__Group__0");
			builder.put(grammarAccess.getServiceAccess().getGroup(), "rule__Service__Group__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_0_0(), "rule__Service__Group_3_0_0__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_0_1(), "rule__Service__Group_3_0_1__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_1(), "rule__Service__Group_3_1__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_2(), "rule__Service__Group_3_2__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_3(), "rule__Service__Group_3_3__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_4(), "rule__Service__Group_3_4__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_5(), "rule__Service__Group_3_5__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_6(), "rule__Service__Group_3_6__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_7(), "rule__Service__Group_3_7__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_7_1(), "rule__Service__Group_3_7_1__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_8(), "rule__Service__Group_3_8__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_9(), "rule__Service__Group_3_9__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_10(), "rule__Service__Group_3_10__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_10_1_0(), "rule__Service__Group_3_10_1_0__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_10_1_1(), "rule__Service__Group_3_10_1_1__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_11(), "rule__Service__Group_3_11__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_11_1_0(), "rule__Service__Group_3_11_1_0__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_11_1_1(), "rule__Service__Group_3_11_1_1__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_12(), "rule__Service__Group_3_12__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_12_1_0(), "rule__Service__Group_3_12_1_0__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_12_1_1(), "rule__Service__Group_3_12_1_1__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_13(), "rule__Service__Group_3_13__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_13_1(), "rule__Service__Group_3_13_1__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_14(), "rule__Service__Group_3_14__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_14_1_0(), "rule__Service__Group_3_14_1_0__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_15(), "rule__Service__Group_3_15__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_15_1(), "rule__Service__Group_3_15_1__0");
			builder.put(grammarAccess.getPortAccess().getGroup(), "rule__Port__Group__0");
			builder.put(grammarAccess.getDeviceAccess().getGroup(), "rule__Device__Group__0");
			builder.put(grammarAccess.getImageAccess().getGroup_1(), "rule__Image__Group_1__0");
			builder.put(grammarAccess.getImageAccess().getGroup_1_1(), "rule__Image__Group_1_1__0");
			builder.put(grammarAccess.getLinkAccess().getGroup(), "rule__Link__Group__0");
			builder.put(grammarAccess.getLinkAccess().getGroup_2(), "rule__Link__Group_2__0");
			builder.put(grammarAccess.getDependency_shortAccess().getGroup(), "rule__Dependency_short__Group__0");
			builder.put(grammarAccess.getDependency_longAccess().getGroup(), "rule__Dependency_long__Group__0");
			builder.put(grammarAccess.getNetworkConnectorAccess().getGroup(), "rule__NetworkConnector__Group__0");
			builder.put(grammarAccess.getNetworkConnectorAccess().getGroup_1_0(), "rule__NetworkConnector__Group_1_0__0");
			builder.put(grammarAccess.getNetworkConnectorAccess().getGroup_1_1(), "rule__NetworkConnector__Group_1_1__0");
			builder.put(grammarAccess.getNetworkConnectorAccess().getGroup_1_1_2_0(), "rule__NetworkConnector__Group_1_1_2_0__0");
			builder.put(grammarAccess.getNetworkConnectorAccess().getGroup_1_1_2_1(), "rule__NetworkConnector__Group_1_1_2_1__0");
			builder.put(grammarAccess.getNetworkConnectorAccess().getGroup_1_1_2_2(), "rule__NetworkConnector__Group_1_1_2_2__0");
			builder.put(grammarAccess.getNetworkConnectorAccess().getGroup_1_1_2_2_1(), "rule__NetworkConnector__Group_1_1_2_2_1__0");
			builder.put(grammarAccess.getNetworkConnectorAccess().getGroup_1_1_2_3(), "rule__NetworkConnector__Group_1_1_2_3__0");
			builder.put(grammarAccess.getNetworkConnectorAccess().getGroup_1_1_2_3_1(), "rule__NetworkConnector__Group_1_1_2_3_1__0");
			builder.put(grammarAccess.getAliasAccess().getGroup(), "rule__Alias__Group__0");
			builder.put(grammarAccess.getVolumeConnector_longAccess().getGroup(), "rule__VolumeConnector_long__Group__0");
			builder.put(grammarAccess.getVolumeConnector_longAccess().getGroup_1_0(), "rule__VolumeConnector_long__Group_1_0__0");
			builder.put(grammarAccess.getVolumeConnector_longAccess().getGroup_1_1(), "rule__VolumeConnector_long__Group_1_1__0");
			builder.put(grammarAccess.getVolumeConnector_longAccess().getGroup_1_2(), "rule__VolumeConnector_long__Group_1_2__0");
			builder.put(grammarAccess.getVolumeConnector_longAccess().getGroup_1_3(), "rule__VolumeConnector_long__Group_1_3__0");
			builder.put(grammarAccess.getVolumeConnector_longAccess().getGroup_1_4(), "rule__VolumeConnector_long__Group_1_4__0");
			builder.put(grammarAccess.getVolumeConnector_longAccess().getGroup_1_5(), "rule__VolumeConnector_long__Group_1_5__0");
			builder.put(grammarAccess.getVolumeConnector_longAccess().getGroup_1_6(), "rule__VolumeConnector_long__Group_1_6__0");
			builder.put(grammarAccess.getVolumeConnector_shortAccess().getGroup(), "rule__VolumeConnector_short__Group__0");
			builder.put(grammarAccess.getVolumeConnector_shortAccess().getGroup_4(), "rule__VolumeConnector_short__Group_4__0");
			builder.put(grammarAccess.getConfigConnector_longAccess().getGroup(), "rule__ConfigConnector_long__Group__0");
			builder.put(grammarAccess.getConfigConnector_longAccess().getGroup_1_0(), "rule__ConfigConnector_long__Group_1_0__0");
			builder.put(grammarAccess.getConfigConnector_longAccess().getGroup_1_1(), "rule__ConfigConnector_long__Group_1_1__0");
			builder.put(grammarAccess.getConfigConnector_longAccess().getGroup_1_2(), "rule__ConfigConnector_long__Group_1_2__0");
			builder.put(grammarAccess.getConfigConnector_longAccess().getGroup_1_3(), "rule__ConfigConnector_long__Group_1_3__0");
			builder.put(grammarAccess.getConfigConnector_longAccess().getGroup_1_4(), "rule__ConfigConnector_long__Group_1_4__0");
			builder.put(grammarAccess.getConfigConnector_shortAccess().getGroup(), "rule__ConfigConnector_short__Group__0");
			builder.put(grammarAccess.getSecretConnector_longAccess().getGroup(), "rule__SecretConnector_long__Group__0");
			builder.put(grammarAccess.getSecretConnector_longAccess().getGroup_1_0(), "rule__SecretConnector_long__Group_1_0__0");
			builder.put(grammarAccess.getSecretConnector_longAccess().getGroup_1_1(), "rule__SecretConnector_long__Group_1_1__0");
			builder.put(grammarAccess.getSecretConnector_longAccess().getGroup_1_2(), "rule__SecretConnector_long__Group_1_2__0");
			builder.put(grammarAccess.getSecretConnector_longAccess().getGroup_1_3(), "rule__SecretConnector_long__Group_1_3__0");
			builder.put(grammarAccess.getSecretConnector_longAccess().getGroup_1_4(), "rule__SecretConnector_long__Group_1_4__0");
			builder.put(grammarAccess.getSecretConnector_shortAccess().getGroup(), "rule__SecretConnector_short__Group__0");
			builder.put(grammarAccess.getNetworkAccess().getGroup(), "rule__Network__Group__0");
			builder.put(grammarAccess.getNetworkAccess().getGroup_3_0(), "rule__Network__Group_3_0__0");
			builder.put(grammarAccess.getNetworkAccess().getGroup_3_1_0(), "rule__Network__Group_3_1_0__0");
			builder.put(grammarAccess.getNetworkAccess().getGroup_3_1_1(), "rule__Network__Group_3_1_1__0");
			builder.put(grammarAccess.getNetworkAccess().getGroup_3_1_2(), "rule__Network__Group_3_1_2__0");
			builder.put(grammarAccess.getNetworkAccess().getGroup_3_1_3(), "rule__Network__Group_3_1_3__0");
			builder.put(grammarAccess.getNetworkAccess().getGroup_3_1_4(), "rule__Network__Group_3_1_4__0");
			builder.put(grammarAccess.getNetworkAccess().getGroup_3_1_5(), "rule__Network__Group_3_1_5__0");
			builder.put(grammarAccess.getNetworkAccess().getGroup_3_1_6(), "rule__Network__Group_3_1_6__0");
			builder.put(grammarAccess.getNetworkAccess().getGroup_3_1_7(), "rule__Network__Group_3_1_7__0");
			builder.put(grammarAccess.getNetworkAccess().getGroup_3_1_8(), "rule__Network__Group_3_1_8__0");
			builder.put(grammarAccess.getVolumeAccess().getGroup(), "rule__Volume__Group__0");
			builder.put(grammarAccess.getVolumeAccess().getGroup_3_0(), "rule__Volume__Group_3_0__0");
			builder.put(grammarAccess.getVolumeAccess().getGroup_3_1(), "rule__Volume__Group_3_1__0");
			builder.put(grammarAccess.getVolumeAccess().getGroup_3_2(), "rule__Volume__Group_3_2__0");
			builder.put(grammarAccess.getVolumeAccess().getGroup_3_3(), "rule__Volume__Group_3_3__0");
			builder.put(grammarAccess.getVolumeAccess().getGroup_3_4(), "rule__Volume__Group_3_4__0");
			builder.put(grammarAccess.getConfigAccess().getGroup(), "rule__Config__Group__0");
			builder.put(grammarAccess.getConfigAccess().getGroup_3_0(), "rule__Config__Group_3_0__0");
			builder.put(grammarAccess.getConfigAccess().getGroup_3_1(), "rule__Config__Group_3_1__0");
			builder.put(grammarAccess.getConfigAccess().getGroup_3_2(), "rule__Config__Group_3_2__0");
			builder.put(grammarAccess.getSecretAccess().getGroup(), "rule__Secret__Group__0");
			builder.put(grammarAccess.getSecretAccess().getGroup_3_0(), "rule__Secret__Group_3_0__0");
			builder.put(grammarAccess.getSecretAccess().getGroup_3_1(), "rule__Secret__Group_3_1__0");
			builder.put(grammarAccess.getSecretAccess().getGroup_3_2(), "rule__Secret__Group_3_2__0");
			builder.put(grammarAccess.getSecretAccess().getGroup_3_3(), "rule__Secret__Group_3_3__0");
			builder.put(grammarAccess.getVolumeLabelAccess().getGroup(), "rule__VolumeLabel__Group__0");
			builder.put(grammarAccess.getVolumeDriverOptAccess().getGroup(), "rule__VolumeDriverOpt__Group__0");
			builder.put(grammarAccess.getNetworkLabelAccess().getGroup(), "rule__NetworkLabel__Group__0");
			builder.put(grammarAccess.getNetworkDriverOptAccess().getGroup(), "rule__NetworkDriverOpt__Group__0");
			builder.put(grammarAccess.getIPAMAccess().getGroup(), "rule__IPAM__Group__0");
			builder.put(grammarAccess.getIPAMAccess().getGroup_1_0(), "rule__IPAM__Group_1_0__0");
			builder.put(grammarAccess.getIPAMAccess().getGroup_1_1(), "rule__IPAM__Group_1_1__0");
			builder.put(grammarAccess.getIPAMAccess().getGroup_1_1_1(), "rule__IPAM__Group_1_1_1__0");
			builder.put(grammarAccess.getIPAMAccess().getGroup_1_2(), "rule__IPAM__Group_1_2__0");
			builder.put(grammarAccess.getIPAMConfigAccess().getGroup(), "rule__IPAMConfig__Group__0");
			builder.put(grammarAccess.getIPAMConfigAccess().getGroup_1_0(), "rule__IPAMConfig__Group_1_0__0");
			builder.put(grammarAccess.getIPAMConfigAccess().getGroup_1_1(), "rule__IPAMConfig__Group_1_1__0");
			builder.put(grammarAccess.getIPAMConfigAccess().getGroup_1_2(), "rule__IPAMConfig__Group_1_2__0");
			builder.put(grammarAccess.getIPAMConfigAccess().getGroup_1_3(), "rule__IPAMConfig__Group_1_3__0");
			builder.put(grammarAccess.getIPAMOptionAccess().getGroup(), "rule__IPAMOption__Group__0");
			builder.put(grammarAccess.getIPAMAddressAccess().getGroup(), "rule__IPAMAddress__Group__0");
			builder.put(grammarAccess.getPATHAccess().getGroup(), "rule__PATH__Group__0");
			builder.put(grammarAccess.getDNSAccess().getGroup(), "rule__DNS__Group__0");
			builder.put(grammarAccess.getNetworkAddressAccess().getGroup(), "rule__NetworkAddress__Group__0");
			builder.put(grammarAccess.getDockerComposeAccess().getVersionAssignment_0_1(), "rule__DockerCompose__VersionAssignment_0_1");
			builder.put(grammarAccess.getDockerComposeAccess().getServicesAssignment_1_1(), "rule__DockerCompose__ServicesAssignment_1_1");
			builder.put(grammarAccess.getDockerComposeAccess().getVolumesAssignment_2_1(), "rule__DockerCompose__VolumesAssignment_2_1");
			builder.put(grammarAccess.getDockerComposeAccess().getConfigsAssignment_3_1(), "rule__DockerCompose__ConfigsAssignment_3_1");
			builder.put(grammarAccess.getDockerComposeAccess().getSecretsAssignment_4_1(), "rule__DockerCompose__SecretsAssignment_4_1");
			builder.put(grammarAccess.getDockerComposeAccess().getNetworksAssignment_5_1(), "rule__DockerCompose__NetworksAssignment_5_1");
			builder.put(grammarAccess.getServiceAccess().getNameAssignment_1(), "rule__Service__NameAssignment_1");
			builder.put(grammarAccess.getServiceAccess().getBuildAssignment_3_0_0_1(), "rule__Service__BuildAssignment_3_0_0_1");
			builder.put(grammarAccess.getServiceAccess().getImageAssignment_3_0_1_1(), "rule__Service__ImageAssignment_3_0_1_1");
			builder.put(grammarAccess.getServiceAccess().getCpu_countAssignment_3_1_1(), "rule__Service__Cpu_countAssignment_3_1_1");
			builder.put(grammarAccess.getServiceAccess().getCommandAssignment_3_2_1(), "rule__Service__CommandAssignment_3_2_1");
			builder.put(grammarAccess.getServiceAccess().getContainer_nameAssignment_3_3_1(), "rule__Service__Container_nameAssignment_3_3_1");
			builder.put(grammarAccess.getServiceAccess().getRestartAssignment_3_4_1(), "rule__Service__RestartAssignment_3_4_1");
			builder.put(grammarAccess.getServiceAccess().getInitAssignment_3_5_1(), "rule__Service__InitAssignment_3_5_1");
			builder.put(grammarAccess.getServiceAccess().getRead_onlyAssignment_3_6_1(), "rule__Service__Read_onlyAssignment_3_6_1");
			builder.put(grammarAccess.getServiceAccess().getLinksAssignment_3_7_1_1(), "rule__Service__LinksAssignment_3_7_1_1");
			builder.put(grammarAccess.getServiceAccess().getDepends_onAssignment_3_8_1_0(), "rule__Service__Depends_onAssignment_3_8_1_0");
			builder.put(grammarAccess.getServiceAccess().getDepends_onAssignment_3_8_1_1(), "rule__Service__Depends_onAssignment_3_8_1_1");
			builder.put(grammarAccess.getServiceAccess().getNetworksAssignment_3_9_1(), "rule__Service__NetworksAssignment_3_9_1");
			builder.put(grammarAccess.getServiceAccess().getVolumesAssignment_3_10_1_0_1(), "rule__Service__VolumesAssignment_3_10_1_0_1");
			builder.put(grammarAccess.getServiceAccess().getVolumesAssignment_3_10_1_1_1(), "rule__Service__VolumesAssignment_3_10_1_1_1");
			builder.put(grammarAccess.getServiceAccess().getConfigsAssignment_3_11_1_0_1(), "rule__Service__ConfigsAssignment_3_11_1_0_1");
			builder.put(grammarAccess.getServiceAccess().getConfigsAssignment_3_11_1_1_1(), "rule__Service__ConfigsAssignment_3_11_1_1_1");
			builder.put(grammarAccess.getServiceAccess().getSecretsAssignment_3_12_1_0_1(), "rule__Service__SecretsAssignment_3_12_1_0_1");
			builder.put(grammarAccess.getServiceAccess().getSecretsAssignment_3_12_1_1_1(), "rule__Service__SecretsAssignment_3_12_1_1_1");
			builder.put(grammarAccess.getServiceAccess().getDevicesAssignment_3_13_1_1(), "rule__Service__DevicesAssignment_3_13_1_1");
			builder.put(grammarAccess.getServiceAccess().getDnsAssignment_3_14_1_0_1(), "rule__Service__DnsAssignment_3_14_1_0_1");
			builder.put(grammarAccess.getServiceAccess().getDnsAssignment_3_14_1_1(), "rule__Service__DnsAssignment_3_14_1_1");
			builder.put(grammarAccess.getServiceAccess().getPortsAssignment_3_15_1_1(), "rule__Service__PortsAssignment_3_15_1_1");
			builder.put(grammarAccess.getPortAccess().getValueAssignment_1(), "rule__Port__ValueAssignment_1");
			builder.put(grammarAccess.getDeviceAccess().getValueAssignment_1(), "rule__Device__ValueAssignment_1");
			builder.put(grammarAccess.getLinkAccess().getServiceAssignment_1(), "rule__Link__ServiceAssignment_1");
			builder.put(grammarAccess.getLinkAccess().getAliasAssignment_2_1(), "rule__Link__AliasAssignment_2_1");
			builder.put(grammarAccess.getDependency_shortAccess().getServiceAssignment_2(), "rule__Dependency_short__ServiceAssignment_2");
			builder.put(grammarAccess.getDependency_longAccess().getServiceAssignment_1(), "rule__Dependency_long__ServiceAssignment_1");
			builder.put(grammarAccess.getDependency_longAccess().getConditionAssignment_4(), "rule__Dependency_long__ConditionAssignment_4");
			builder.put(grammarAccess.getNetworkConnectorAccess().getNetworkAssignment_1_0_1(), "rule__NetworkConnector__NetworkAssignment_1_0_1");
			builder.put(grammarAccess.getNetworkConnectorAccess().getNetworkAssignment_1_1_0(), "rule__NetworkConnector__NetworkAssignment_1_1_0");
			builder.put(grammarAccess.getNetworkConnectorAccess().getIpv4_addressAssignment_1_1_2_0_1(), "rule__NetworkConnector__Ipv4_addressAssignment_1_1_2_0_1");
			builder.put(grammarAccess.getNetworkConnectorAccess().getPriorityAssignment_1_1_2_1_1(), "rule__NetworkConnector__PriorityAssignment_1_1_2_1_1");
			builder.put(grammarAccess.getNetworkConnectorAccess().getAliasesAssignment_1_1_2_2_1_1(), "rule__NetworkConnector__AliasesAssignment_1_1_2_2_1_1");
			builder.put(grammarAccess.getNetworkConnectorAccess().getLink_local_ipsAssignment_1_1_2_3_1_1(), "rule__NetworkConnector__Link_local_ipsAssignment_1_1_2_3_1_1");
			builder.put(grammarAccess.getAliasAccess().getAliasAssignment_1(), "rule__Alias__AliasAssignment_1");
			builder.put(grammarAccess.getVolumeConnector_longAccess().getVolumeAssignment_1_0_1(), "rule__VolumeConnector_long__VolumeAssignment_1_0_1");
			builder.put(grammarAccess.getVolumeConnector_longAccess().getTypeAssignment_1_1_1(), "rule__VolumeConnector_long__TypeAssignment_1_1_1");
			builder.put(grammarAccess.getVolumeConnector_longAccess().getContainer_pathAssignment_1_2_1(), "rule__VolumeConnector_long__Container_pathAssignment_1_2_1");
			builder.put(grammarAccess.getVolumeConnector_longAccess().getRead_onlyAssignment_1_3_1(), "rule__VolumeConnector_long__Read_onlyAssignment_1_3_1");
			builder.put(grammarAccess.getVolumeConnector_longAccess().getPropagationAssignment_1_4_2(), "rule__VolumeConnector_long__PropagationAssignment_1_4_2");
			builder.put(grammarAccess.getVolumeConnector_longAccess().getNocopyAssignment_1_5_2(), "rule__VolumeConnector_long__NocopyAssignment_1_5_2");
			builder.put(grammarAccess.getVolumeConnector_longAccess().getSizeAssignment_1_6_2(), "rule__VolumeConnector_long__SizeAssignment_1_6_2");
			builder.put(grammarAccess.getVolumeConnector_shortAccess().getVolumeAssignment_1(), "rule__VolumeConnector_short__VolumeAssignment_1");
			builder.put(grammarAccess.getVolumeConnector_shortAccess().getContainer_pathAssignment_3(), "rule__VolumeConnector_short__Container_pathAssignment_3");
			builder.put(grammarAccess.getVolumeConnector_shortAccess().getAccess_modeAssignment_4_1(), "rule__VolumeConnector_short__Access_modeAssignment_4_1");
			builder.put(grammarAccess.getConfigConnector_longAccess().getConfigAssignment_1_0_1(), "rule__ConfigConnector_long__ConfigAssignment_1_0_1");
			builder.put(grammarAccess.getConfigConnector_longAccess().getTargetAssignment_1_1_1(), "rule__ConfigConnector_long__TargetAssignment_1_1_1");
			builder.put(grammarAccess.getConfigConnector_longAccess().getUidAssignment_1_2_1(), "rule__ConfigConnector_long__UidAssignment_1_2_1");
			builder.put(grammarAccess.getConfigConnector_longAccess().getGidAssignment_1_3_1(), "rule__ConfigConnector_long__GidAssignment_1_3_1");
			builder.put(grammarAccess.getConfigConnector_longAccess().getModeAssignment_1_4_1(), "rule__ConfigConnector_long__ModeAssignment_1_4_1");
			builder.put(grammarAccess.getConfigConnector_shortAccess().getConfigAssignment_1(), "rule__ConfigConnector_short__ConfigAssignment_1");
			builder.put(grammarAccess.getSecretConnector_longAccess().getSecretAssignment_1_0_1(), "rule__SecretConnector_long__SecretAssignment_1_0_1");
			builder.put(grammarAccess.getSecretConnector_longAccess().getTargetAssignment_1_1_1(), "rule__SecretConnector_long__TargetAssignment_1_1_1");
			builder.put(grammarAccess.getSecretConnector_longAccess().getUidAssignment_1_2_1(), "rule__SecretConnector_long__UidAssignment_1_2_1");
			builder.put(grammarAccess.getSecretConnector_longAccess().getGidAssignment_1_3_1(), "rule__SecretConnector_long__GidAssignment_1_3_1");
			builder.put(grammarAccess.getSecretConnector_longAccess().getModeAssignment_1_4_1(), "rule__SecretConnector_long__ModeAssignment_1_4_1");
			builder.put(grammarAccess.getSecretConnector_shortAccess().getSecretAssignment_1(), "rule__SecretConnector_short__SecretAssignment_1");
			builder.put(grammarAccess.getNetworkAccess().getNameAssignment_1(), "rule__Network__NameAssignment_1");
			builder.put(grammarAccess.getNetworkAccess().getDriverAssignment_3_1_0_1(), "rule__Network__DriverAssignment_3_1_0_1");
			builder.put(grammarAccess.getNetworkAccess().getAttachableAssignment_3_1_1_1(), "rule__Network__AttachableAssignment_3_1_1_1");
			builder.put(grammarAccess.getNetworkAccess().getEnable_ipv6Assignment_3_1_2_1(), "rule__Network__Enable_ipv6Assignment_3_1_2_1");
			builder.put(grammarAccess.getNetworkAccess().getInternalAssignment_3_1_3_1(), "rule__Network__InternalAssignment_3_1_3_1");
			builder.put(grammarAccess.getNetworkAccess().getExternalAssignment_3_1_4_1(), "rule__Network__ExternalAssignment_3_1_4_1");
			builder.put(grammarAccess.getNetworkAccess().getNetwork_nameAssignment_3_1_5_1(), "rule__Network__Network_nameAssignment_3_1_5_1");
			builder.put(grammarAccess.getNetworkAccess().getLabelsAssignment_3_1_6_1(), "rule__Network__LabelsAssignment_3_1_6_1");
			builder.put(grammarAccess.getNetworkAccess().getDriver_optsAssignment_3_1_7_1(), "rule__Network__Driver_optsAssignment_3_1_7_1");
			builder.put(grammarAccess.getNetworkAccess().getIpamAssignment_3_1_8_1(), "rule__Network__IpamAssignment_3_1_8_1");
			builder.put(grammarAccess.getVolumeAccess().getNameAssignment_1(), "rule__Volume__NameAssignment_1");
			builder.put(grammarAccess.getVolumeAccess().getExternalAssignment_3_0_1(), "rule__Volume__ExternalAssignment_3_0_1");
			builder.put(grammarAccess.getVolumeAccess().getDriverAssignment_3_1_1(), "rule__Volume__DriverAssignment_3_1_1");
			builder.put(grammarAccess.getVolumeAccess().getVolume_nameAssignment_3_2_1(), "rule__Volume__Volume_nameAssignment_3_2_1");
			builder.put(grammarAccess.getVolumeAccess().getLabelsAssignment_3_3_1(), "rule__Volume__LabelsAssignment_3_3_1");
			builder.put(grammarAccess.getVolumeAccess().getDriver_optsAssignment_3_4_1(), "rule__Volume__Driver_optsAssignment_3_4_1");
			builder.put(grammarAccess.getConfigAccess().getNameAssignment_1(), "rule__Config__NameAssignment_1");
			builder.put(grammarAccess.getConfigAccess().getExternalAssignment_3_0_1(), "rule__Config__ExternalAssignment_3_0_1");
			builder.put(grammarAccess.getConfigAccess().getFileAssignment_3_1_1(), "rule__Config__FileAssignment_3_1_1");
			builder.put(grammarAccess.getConfigAccess().getConfig_nameAssignment_3_2_1(), "rule__Config__Config_nameAssignment_3_2_1");
			builder.put(grammarAccess.getSecretAccess().getNameAssignment_1(), "rule__Secret__NameAssignment_1");
			builder.put(grammarAccess.getSecretAccess().getExternalAssignment_3_0_1(), "rule__Secret__ExternalAssignment_3_0_1");
			builder.put(grammarAccess.getSecretAccess().getFileAssignment_3_1_1(), "rule__Secret__FileAssignment_3_1_1");
			builder.put(grammarAccess.getSecretAccess().getEnvironmentAssignment_3_2_1(), "rule__Secret__EnvironmentAssignment_3_2_1");
			builder.put(grammarAccess.getSecretAccess().getSecret_nameAssignment_3_3_1(), "rule__Secret__Secret_nameAssignment_3_3_1");
			builder.put(grammarAccess.getVolumeLabelAccess().getNameAssignment_1(), "rule__VolumeLabel__NameAssignment_1");
			builder.put(grammarAccess.getVolumeLabelAccess().getValueAssignment_3(), "rule__VolumeLabel__ValueAssignment_3");
			builder.put(grammarAccess.getVolumeDriverOptAccess().getNameAssignment_1(), "rule__VolumeDriverOpt__NameAssignment_1");
			builder.put(grammarAccess.getVolumeDriverOptAccess().getValueAssignment_3(), "rule__VolumeDriverOpt__ValueAssignment_3");
			builder.put(grammarAccess.getNetworkLabelAccess().getNameAssignment_1(), "rule__NetworkLabel__NameAssignment_1");
			builder.put(grammarAccess.getNetworkLabelAccess().getValueAssignment_3(), "rule__NetworkLabel__ValueAssignment_3");
			builder.put(grammarAccess.getNetworkDriverOptAccess().getNameAssignment_1(), "rule__NetworkDriverOpt__NameAssignment_1");
			builder.put(grammarAccess.getNetworkDriverOptAccess().getValueAssignment_3(), "rule__NetworkDriverOpt__ValueAssignment_3");
			builder.put(grammarAccess.getIPAMAccess().getDriverAssignment_1_0_1(), "rule__IPAM__DriverAssignment_1_0_1");
			builder.put(grammarAccess.getIPAMAccess().getConfigsAssignment_1_1_1_1(), "rule__IPAM__ConfigsAssignment_1_1_1_1");
			builder.put(grammarAccess.getIPAMAccess().getOptionsAssignment_1_2_1(), "rule__IPAM__OptionsAssignment_1_2_1");
			builder.put(grammarAccess.getIPAMConfigAccess().getSubnetAssignment_1_0_1(), "rule__IPAMConfig__SubnetAssignment_1_0_1");
			builder.put(grammarAccess.getIPAMConfigAccess().getIp_rangeAssignment_1_1_1(), "rule__IPAMConfig__Ip_rangeAssignment_1_1_1");
			builder.put(grammarAccess.getIPAMConfigAccess().getGatewayAssignment_1_2_1(), "rule__IPAMConfig__GatewayAssignment_1_2_1");
			builder.put(grammarAccess.getIPAMConfigAccess().getAux_addressesAssignment_1_3_1(), "rule__IPAMConfig__Aux_addressesAssignment_1_3_1");
			builder.put(grammarAccess.getIPAMOptionAccess().getNameAssignment_1(), "rule__IPAMOption__NameAssignment_1");
			builder.put(grammarAccess.getIPAMOptionAccess().getValueAssignment_3(), "rule__IPAMOption__ValueAssignment_3");
			builder.put(grammarAccess.getIPAMAddressAccess().getNameAssignment_1(), "rule__IPAMAddress__NameAssignment_1");
			builder.put(grammarAccess.getIPAMAddressAccess().getDnsAssignment_3(), "rule__IPAMAddress__DnsAssignment_3");
			builder.put(grammarAccess.getDNSAccess().getDns1Assignment_0(), "rule__DNS__Dns1Assignment_0");
			builder.put(grammarAccess.getDNSAccess().getDns2Assignment_2(), "rule__DNS__Dns2Assignment_2");
			builder.put(grammarAccess.getDNSAccess().getDns3Assignment_4(), "rule__DNS__Dns3Assignment_4");
			builder.put(grammarAccess.getDNSAccess().getDns4Assignment_6(), "rule__DNS__Dns4Assignment_6");
			builder.put(grammarAccess.getNetworkAddressAccess().getDns1Assignment_0(), "rule__NetworkAddress__Dns1Assignment_0");
			builder.put(grammarAccess.getNetworkAddressAccess().getDns2Assignment_2(), "rule__NetworkAddress__Dns2Assignment_2");
			builder.put(grammarAccess.getNetworkAddressAccess().getDns3Assignment_4(), "rule__NetworkAddress__Dns3Assignment_4");
			builder.put(grammarAccess.getNetworkAddressAccess().getDns4Assignment_6(), "rule__NetworkAddress__Dns4Assignment_6");
			builder.put(grammarAccess.getNetworkAddressAccess().getNetIdAssignment_8(), "rule__NetworkAddress__NetIdAssignment_8");
			builder.put(grammarAccess.getDockerComposeAccess().getUnorderedGroup(), "rule__DockerCompose__UnorderedGroup");
			builder.put(grammarAccess.getServiceAccess().getUnorderedGroup_3(), "rule__Service__UnorderedGroup_3");
			builder.put(grammarAccess.getNetworkConnectorAccess().getUnorderedGroup_1_1_2(), "rule__NetworkConnector__UnorderedGroup_1_1_2");
			builder.put(grammarAccess.getVolumeConnector_longAccess().getUnorderedGroup_1(), "rule__VolumeConnector_long__UnorderedGroup_1");
			builder.put(grammarAccess.getConfigConnector_longAccess().getUnorderedGroup_1(), "rule__ConfigConnector_long__UnorderedGroup_1");
			builder.put(grammarAccess.getSecretConnector_longAccess().getUnorderedGroup_1(), "rule__SecretConnector_long__UnorderedGroup_1");
			builder.put(grammarAccess.getNetworkAccess().getUnorderedGroup_3_1(), "rule__Network__UnorderedGroup_3_1");
			builder.put(grammarAccess.getVolumeAccess().getUnorderedGroup_3(), "rule__Volume__UnorderedGroup_3");
			builder.put(grammarAccess.getConfigAccess().getUnorderedGroup_3(), "rule__Config__UnorderedGroup_3");
			builder.put(grammarAccess.getSecretAccess().getUnorderedGroup_3(), "rule__Secret__UnorderedGroup_3");
			builder.put(grammarAccess.getIPAMAccess().getUnorderedGroup_1(), "rule__IPAM__UnorderedGroup_1");
			builder.put(grammarAccess.getIPAMConfigAccess().getUnorderedGroup_1(), "rule__IPAMConfig__UnorderedGroup_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private DockerComposeGrammarAccess grammarAccess;

	@Override
	protected InternalDockerComposeParser createParser() {
		InternalDockerComposeParser result = new InternalDockerComposeParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DockerComposeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DockerComposeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
