/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.dockercompose.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.dockercompose.ide.contentassist.antlr.internal.InternalDockerComposeParser;
import org.xtext.example.dockercompose.services.DockerComposeGrammarAccess;

public class DockerComposeParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(DockerComposeGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, DockerComposeGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getVersionAccess().getAlternatives(), "rule__Version__Alternatives");
			builder.put(grammarAccess.getQuotedIntAccess().getAlternatives(), "rule__QuotedInt__Alternatives");
			builder.put(grammarAccess.getServiceAccess().getAlternatives_3_10_1(), "rule__Service__Alternatives_3_10_1");
			builder.put(grammarAccess.getServiceAccess().getAlternatives_3_14_1(), "rule__Service__Alternatives_3_14_1");
			builder.put(grammarAccess.getServiceAccess().getAlternatives_3_16_1(), "rule__Service__Alternatives_3_16_1");
			builder.put(grammarAccess.getEnvironmentVariableMapAccess().getAlternatives_3(), "rule__EnvironmentVariableMap__Alternatives_3");
			builder.put(grammarAccess.getEnvironmentVariableListAccess().getAlternatives_3_1(), "rule__EnvironmentVariableList__Alternatives_3_1");
			builder.put(grammarAccess.getImageAccess().getAlternatives_0_1_1(), "rule__Image__Alternatives_0_1_1");
			builder.put(grammarAccess.getImageAccess().getAlternatives_1_1_1(), "rule__Image__Alternatives_1_1_1");
			builder.put(grammarAccess.getImageAccess().getAlternatives_3(), "rule__Image__Alternatives_3");
			builder.put(grammarAccess.getImageAccess().getAlternatives_3_0_1(), "rule__Image__Alternatives_3_0_1");
			builder.put(grammarAccess.getImageAccess().getAlternatives_3_1_2_1(), "rule__Image__Alternatives_3_1_2_1");
			builder.put(grammarAccess.getDependencyAccess().getAlternatives_1(), "rule__Dependency__Alternatives_1");
			builder.put(grammarAccess.getVolumeConnectorAccess().getAlternatives_1(), "rule__VolumeConnector__Alternatives_1");
			builder.put(grammarAccess.getConfigConnectorAccess().getAlternatives_1(), "rule__ConfigConnector__Alternatives_1");
			builder.put(grammarAccess.getSecretConnectorAccess().getAlternatives_1(), "rule__SecretConnector__Alternatives_1");
			builder.put(grammarAccess.getNetworkAccess().getAlternatives_3(), "rule__Network__Alternatives_3");
			builder.put(grammarAccess.getPortsAccess().getAlternatives(), "rule__Ports__Alternatives");
			builder.put(grammarAccess.getPATHAccess().getAlternatives(), "rule__PATH__Alternatives");
			builder.put(grammarAccess.getPATHAccess().getAlternatives_0_0(), "rule__PATH__Alternatives_0_0");
			builder.put(grammarAccess.getPATHAccess().getAlternatives_0_1_1(), "rule__PATH__Alternatives_0_1_1");
			builder.put(grammarAccess.getPATHAccess().getAlternatives_1_1_0(), "rule__PATH__Alternatives_1_1_0");
			builder.put(grammarAccess.getPATHAccess().getAlternatives_1_2(), "rule__PATH__Alternatives_1_2");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getCommandAccess().getAlternatives(), "rule__Command__Alternatives");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getRestartPolicyAccess().getAlternatives(), "rule__RestartPolicy__Alternatives");
			builder.put(grammarAccess.getAccessModeAccess().getAlternatives(), "rule__AccessMode__Alternatives");
			builder.put(grammarAccess.getMountTypeAccess().getAlternatives(), "rule__MountType__Alternatives");
			builder.put(grammarAccess.getPropagationTypeAccess().getAlternatives(), "rule__PropagationType__Alternatives");
			builder.put(grammarAccess.getConditionAccess().getAlternatives(), "rule__Condition__Alternatives");
			builder.put(grammarAccess.getDockerComposeAccess().getGroup_0(), "rule__DockerCompose__Group_0__0");
			builder.put(grammarAccess.getDockerComposeAccess().getGroup_1(), "rule__DockerCompose__Group_1__0");
			builder.put(grammarAccess.getDockerComposeAccess().getGroup_2(), "rule__DockerCompose__Group_2__0");
			builder.put(grammarAccess.getDockerComposeAccess().getGroup_3(), "rule__DockerCompose__Group_3__0");
			builder.put(grammarAccess.getDockerComposeAccess().getGroup_4(), "rule__DockerCompose__Group_4__0");
			builder.put(grammarAccess.getDockerComposeAccess().getGroup_5(), "rule__DockerCompose__Group_5__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup(), "rule__EDouble__Group__0");
			builder.put(grammarAccess.getServiceAccess().getGroup(), "rule__Service__Group__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_0(), "rule__Service__Group_3_0__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_1(), "rule__Service__Group_3_1__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_2(), "rule__Service__Group_3_2__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_3(), "rule__Service__Group_3_3__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_4(), "rule__Service__Group_3_4__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_5(), "rule__Service__Group_3_5__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_6(), "rule__Service__Group_3_6__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_7(), "rule__Service__Group_3_7__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_8(), "rule__Service__Group_3_8__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_8_1(), "rule__Service__Group_3_8_1__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_9(), "rule__Service__Group_3_9__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_10(), "rule__Service__Group_3_10__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_11(), "rule__Service__Group_3_11__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_11_1(), "rule__Service__Group_3_11_1__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_12(), "rule__Service__Group_3_12__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_12_1(), "rule__Service__Group_3_12_1__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_13(), "rule__Service__Group_3_13__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_13_1(), "rule__Service__Group_3_13_1__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_14(), "rule__Service__Group_3_14__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_15(), "rule__Service__Group_3_15__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_15_1(), "rule__Service__Group_3_15_1__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_16(), "rule__Service__Group_3_16__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_16_1_0(), "rule__Service__Group_3_16_1_0__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_17(), "rule__Service__Group_3_17__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_17_1(), "rule__Service__Group_3_17_1__0");
			builder.put(grammarAccess.getEnvironmentVariableMapAccess().getGroup(), "rule__EnvironmentVariableMap__Group__0");
			builder.put(grammarAccess.getEnvironmentVariableListAccess().getGroup(), "rule__EnvironmentVariableList__Group__0");
			builder.put(grammarAccess.getEnvironmentVariableListAccess().getGroup_3(), "rule__EnvironmentVariableList__Group_3__0");
			builder.put(grammarAccess.getPortAccess().getGroup(), "rule__Port__Group__0");
			builder.put(grammarAccess.getDeviceAccess().getGroup(), "rule__Device__Group__0");
			builder.put(grammarAccess.getImageAccess().getGroup(), "rule__Image__Group__0");
			builder.put(grammarAccess.getImageAccess().getGroup_0(), "rule__Image__Group_0__0");
			builder.put(grammarAccess.getImageAccess().getGroup_0_1(), "rule__Image__Group_0_1__0");
			builder.put(grammarAccess.getImageAccess().getGroup_1(), "rule__Image__Group_1__0");
			builder.put(grammarAccess.getImageAccess().getGroup_1_1(), "rule__Image__Group_1_1__0");
			builder.put(grammarAccess.getImageAccess().getGroup_3_0(), "rule__Image__Group_3_0__0");
			builder.put(grammarAccess.getImageAccess().getGroup_3_0_1_2(), "rule__Image__Group_3_0_1_2__0");
			builder.put(grammarAccess.getImageAccess().getGroup_3_1(), "rule__Image__Group_3_1__0");
			builder.put(grammarAccess.getImageAccess().getGroup_3_1_2(), "rule__Image__Group_3_1_2__0");
			builder.put(grammarAccess.getLinkAccess().getGroup(), "rule__Link__Group__0");
			builder.put(grammarAccess.getLinkAccess().getGroup_2(), "rule__Link__Group_2__0");
			builder.put(grammarAccess.getDependencyAccess().getGroup(), "rule__Dependency__Group__0");
			builder.put(grammarAccess.getDependencyAccess().getGroup_1_0(), "rule__Dependency__Group_1_0__0");
			builder.put(grammarAccess.getDependencyAccess().getGroup_1_1(), "rule__Dependency__Group_1_1__0");
			builder.put(grammarAccess.getNetworkConnector_longAccess().getGroup(), "rule__NetworkConnector_long__Group__0");
			builder.put(grammarAccess.getNetworkConnector_longAccess().getGroup_3_0(), "rule__NetworkConnector_long__Group_3_0__0");
			builder.put(grammarAccess.getNetworkConnector_longAccess().getGroup_3_1(), "rule__NetworkConnector_long__Group_3_1__0");
			builder.put(grammarAccess.getNetworkConnector_longAccess().getGroup_3_2(), "rule__NetworkConnector_long__Group_3_2__0");
			builder.put(grammarAccess.getNetworkConnector_longAccess().getGroup_3_2_1(), "rule__NetworkConnector_long__Group_3_2_1__0");
			builder.put(grammarAccess.getNetworkConnector_longAccess().getGroup_3_3(), "rule__NetworkConnector_long__Group_3_3__0");
			builder.put(grammarAccess.getNetworkConnector_longAccess().getGroup_3_3_1(), "rule__NetworkConnector_long__Group_3_3_1__0");
			builder.put(grammarAccess.getNetworkConnector_shortAccess().getGroup(), "rule__NetworkConnector_short__Group__0");
			builder.put(grammarAccess.getAliasAccess().getGroup(), "rule__Alias__Group__0");
			builder.put(grammarAccess.getVolumeConnectorAccess().getGroup(), "rule__VolumeConnector__Group__0");
			builder.put(grammarAccess.getVolumeConnectorAccess().getGroup_1_0(), "rule__VolumeConnector__Group_1_0__0");
			builder.put(grammarAccess.getVolumeConnectorAccess().getGroup_1_0_3(), "rule__VolumeConnector__Group_1_0_3__0");
			builder.put(grammarAccess.getVolumeConnectorAccess().getGroup_1_1_0(), "rule__VolumeConnector__Group_1_1_0__0");
			builder.put(grammarAccess.getVolumeConnectorAccess().getGroup_1_1_1(), "rule__VolumeConnector__Group_1_1_1__0");
			builder.put(grammarAccess.getVolumeConnectorAccess().getGroup_1_1_2(), "rule__VolumeConnector__Group_1_1_2__0");
			builder.put(grammarAccess.getVolumeConnectorAccess().getGroup_1_1_3(), "rule__VolumeConnector__Group_1_1_3__0");
			builder.put(grammarAccess.getVolumeConnectorAccess().getGroup_1_1_4(), "rule__VolumeConnector__Group_1_1_4__0");
			builder.put(grammarAccess.getVolumeConnectorAccess().getGroup_1_1_5(), "rule__VolumeConnector__Group_1_1_5__0");
			builder.put(grammarAccess.getVolumeConnectorAccess().getGroup_1_1_6(), "rule__VolumeConnector__Group_1_1_6__0");
			builder.put(grammarAccess.getConfigConnectorAccess().getGroup(), "rule__ConfigConnector__Group__0");
			builder.put(grammarAccess.getConfigConnectorAccess().getGroup_1_1_0(), "rule__ConfigConnector__Group_1_1_0__0");
			builder.put(grammarAccess.getConfigConnectorAccess().getGroup_1_1_1(), "rule__ConfigConnector__Group_1_1_1__0");
			builder.put(grammarAccess.getConfigConnectorAccess().getGroup_1_1_2(), "rule__ConfigConnector__Group_1_1_2__0");
			builder.put(grammarAccess.getConfigConnectorAccess().getGroup_1_1_3(), "rule__ConfigConnector__Group_1_1_3__0");
			builder.put(grammarAccess.getConfigConnectorAccess().getGroup_1_1_4(), "rule__ConfigConnector__Group_1_1_4__0");
			builder.put(grammarAccess.getSecretConnectorAccess().getGroup(), "rule__SecretConnector__Group__0");
			builder.put(grammarAccess.getSecretConnectorAccess().getGroup_1_1_0(), "rule__SecretConnector__Group_1_1_0__0");
			builder.put(grammarAccess.getSecretConnectorAccess().getGroup_1_1_1(), "rule__SecretConnector__Group_1_1_1__0");
			builder.put(grammarAccess.getSecretConnectorAccess().getGroup_1_1_2(), "rule__SecretConnector__Group_1_1_2__0");
			builder.put(grammarAccess.getSecretConnectorAccess().getGroup_1_1_3(), "rule__SecretConnector__Group_1_1_3__0");
			builder.put(grammarAccess.getSecretConnectorAccess().getGroup_1_1_4(), "rule__SecretConnector__Group_1_1_4__0");
			builder.put(grammarAccess.getNetworkAccess().getGroup(), "rule__Network__Group__0");
			builder.put(grammarAccess.getNetworkAccess().getGroup_3_0(), "rule__Network__Group_3_0__0");
			builder.put(grammarAccess.getNetworkAccess().getGroup_3_1_0(), "rule__Network__Group_3_1_0__0");
			builder.put(grammarAccess.getNetworkAccess().getGroup_3_1_1(), "rule__Network__Group_3_1_1__0");
			builder.put(grammarAccess.getNetworkAccess().getGroup_3_1_2(), "rule__Network__Group_3_1_2__0");
			builder.put(grammarAccess.getNetworkAccess().getGroup_3_1_3(), "rule__Network__Group_3_1_3__0");
			builder.put(grammarAccess.getNetworkAccess().getGroup_3_1_4(), "rule__Network__Group_3_1_4__0");
			builder.put(grammarAccess.getNetworkAccess().getGroup_3_1_5(), "rule__Network__Group_3_1_5__0");
			builder.put(grammarAccess.getNetworkAccess().getGroup_3_1_6(), "rule__Network__Group_3_1_6__0");
			builder.put(grammarAccess.getNetworkAccess().getGroup_3_1_7(), "rule__Network__Group_3_1_7__0");
			builder.put(grammarAccess.getNetworkAccess().getGroup_3_1_8(), "rule__Network__Group_3_1_8__0");
			builder.put(grammarAccess.getVolumeAccess().getGroup(), "rule__Volume__Group__0");
			builder.put(grammarAccess.getVolumeAccess().getGroup_3_0(), "rule__Volume__Group_3_0__0");
			builder.put(grammarAccess.getVolumeAccess().getGroup_3_1(), "rule__Volume__Group_3_1__0");
			builder.put(grammarAccess.getVolumeAccess().getGroup_3_2(), "rule__Volume__Group_3_2__0");
			builder.put(grammarAccess.getVolumeAccess().getGroup_3_3(), "rule__Volume__Group_3_3__0");
			builder.put(grammarAccess.getVolumeAccess().getGroup_3_4(), "rule__Volume__Group_3_4__0");
			builder.put(grammarAccess.getConfigAccess().getGroup(), "rule__Config__Group__0");
			builder.put(grammarAccess.getConfigAccess().getGroup_3_0(), "rule__Config__Group_3_0__0");
			builder.put(grammarAccess.getConfigAccess().getGroup_3_1(), "rule__Config__Group_3_1__0");
			builder.put(grammarAccess.getConfigAccess().getGroup_3_2(), "rule__Config__Group_3_2__0");
			builder.put(grammarAccess.getSecretAccess().getGroup(), "rule__Secret__Group__0");
			builder.put(grammarAccess.getSecretAccess().getGroup_3_0(), "rule__Secret__Group_3_0__0");
			builder.put(grammarAccess.getSecretAccess().getGroup_3_1(), "rule__Secret__Group_3_1__0");
			builder.put(grammarAccess.getSecretAccess().getGroup_3_2(), "rule__Secret__Group_3_2__0");
			builder.put(grammarAccess.getSecretAccess().getGroup_3_3(), "rule__Secret__Group_3_3__0");
			builder.put(grammarAccess.getVolumeLabelAccess().getGroup(), "rule__VolumeLabel__Group__0");
			builder.put(grammarAccess.getVolumeDriverOptAccess().getGroup(), "rule__VolumeDriverOpt__Group__0");
			builder.put(grammarAccess.getNetworkLabelAccess().getGroup(), "rule__NetworkLabel__Group__0");
			builder.put(grammarAccess.getNetworkDriverOptAccess().getGroup(), "rule__NetworkDriverOpt__Group__0");
			builder.put(grammarAccess.getIPAMAccess().getGroup(), "rule__IPAM__Group__0");
			builder.put(grammarAccess.getIPAMAccess().getGroup_1_0(), "rule__IPAM__Group_1_0__0");
			builder.put(grammarAccess.getIPAMAccess().getGroup_1_1(), "rule__IPAM__Group_1_1__0");
			builder.put(grammarAccess.getIPAMAccess().getGroup_1_1_1(), "rule__IPAM__Group_1_1_1__0");
			builder.put(grammarAccess.getIPAMAccess().getGroup_1_2(), "rule__IPAM__Group_1_2__0");
			builder.put(grammarAccess.getIPAMConfigAccess().getGroup(), "rule__IPAMConfig__Group__0");
			builder.put(grammarAccess.getIPAMConfigAccess().getGroup_1_0(), "rule__IPAMConfig__Group_1_0__0");
			builder.put(grammarAccess.getIPAMConfigAccess().getGroup_1_1(), "rule__IPAMConfig__Group_1_1__0");
			builder.put(grammarAccess.getIPAMConfigAccess().getGroup_1_2(), "rule__IPAMConfig__Group_1_2__0");
			builder.put(grammarAccess.getIPAMConfigAccess().getGroup_1_3(), "rule__IPAMConfig__Group_1_3__0");
			builder.put(grammarAccess.getIPAMOptionAccess().getGroup(), "rule__IPAMOption__Group__0");
			builder.put(grammarAccess.getIPAMAddressAccess().getGroup(), "rule__IPAMAddress__Group__0");
			builder.put(grammarAccess.getPATHAccess().getGroup_0(), "rule__PATH__Group_0__0");
			builder.put(grammarAccess.getPATHAccess().getGroup_0_0_0(), "rule__PATH__Group_0_0_0__0");
			builder.put(grammarAccess.getPATHAccess().getGroup_0_0_0_1(), "rule__PATH__Group_0_0_0_1__0");
			builder.put(grammarAccess.getPATHAccess().getGroup_0_1(), "rule__PATH__Group_0_1__0");
			builder.put(grammarAccess.getPATHAccess().getGroup_0_1_1_0(), "rule__PATH__Group_0_1_1_0__0");
			builder.put(grammarAccess.getPATHAccess().getGroup_0_1_1_0_1(), "rule__PATH__Group_0_1_1_0_1__0");
			builder.put(grammarAccess.getPATHAccess().getGroup_1(), "rule__PATH__Group_1__0");
			builder.put(grammarAccess.getPATHAccess().getGroup_1_1(), "rule__PATH__Group_1_1__0");
			builder.put(grammarAccess.getPATHAccess().getGroup_1_1_0_0(), "rule__PATH__Group_1_1_0_0__0");
			builder.put(grammarAccess.getPATHAccess().getGroup_1_1_0_0_1(), "rule__PATH__Group_1_1_0_0_1__0");
			builder.put(grammarAccess.getPATHAccess().getGroup_1_2_0(), "rule__PATH__Group_1_2_0__0");
			builder.put(grammarAccess.getPATHAccess().getGroup_1_2_0_1(), "rule__PATH__Group_1_2_0_1__0");
			builder.put(grammarAccess.getEStringAccess().getGroup_2(), "rule__EString__Group_2__0");
			builder.put(grammarAccess.getLabelIDAccess().getGroup(), "rule__LabelID__Group__0");
			builder.put(grammarAccess.getLabelIDAccess().getGroup_1(), "rule__LabelID__Group_1__0");
			builder.put(grammarAccess.getDotIDAccess().getGroup(), "rule__DotID__Group__0");
			builder.put(grammarAccess.getDotIDAccess().getGroup_1(), "rule__DotID__Group_1__0");
			builder.put(grammarAccess.getDNSAccess().getGroup(), "rule__DNS__Group__0");
			builder.put(grammarAccess.getNetworkAddressAccess().getGroup(), "rule__NetworkAddress__Group__0");
			builder.put(grammarAccess.getDockerComposeAccess().getVersionAssignment_0_1(), "rule__DockerCompose__VersionAssignment_0_1");
			builder.put(grammarAccess.getDockerComposeAccess().getServicesAssignment_1_1(), "rule__DockerCompose__ServicesAssignment_1_1");
			builder.put(grammarAccess.getDockerComposeAccess().getVolumesAssignment_2_1(), "rule__DockerCompose__VolumesAssignment_2_1");
			builder.put(grammarAccess.getDockerComposeAccess().getConfigsAssignment_3_1(), "rule__DockerCompose__ConfigsAssignment_3_1");
			builder.put(grammarAccess.getDockerComposeAccess().getSecretsAssignment_4_1(), "rule__DockerCompose__SecretsAssignment_4_1");
			builder.put(grammarAccess.getDockerComposeAccess().getNetworksAssignment_5_1(), "rule__DockerCompose__NetworksAssignment_5_1");
			builder.put(grammarAccess.getServiceAccess().getNameAssignment_1(), "rule__Service__NameAssignment_1");
			builder.put(grammarAccess.getServiceAccess().getBuildAssignment_3_0_1(), "rule__Service__BuildAssignment_3_0_1");
			builder.put(grammarAccess.getServiceAccess().getImageAssignment_3_1_1(), "rule__Service__ImageAssignment_3_1_1");
			builder.put(grammarAccess.getServiceAccess().getCpu_countAssignment_3_2_1(), "rule__Service__Cpu_countAssignment_3_2_1");
			builder.put(grammarAccess.getServiceAccess().getCommandAssignment_3_3_1(), "rule__Service__CommandAssignment_3_3_1");
			builder.put(grammarAccess.getServiceAccess().getContainer_nameAssignment_3_4_1(), "rule__Service__Container_nameAssignment_3_4_1");
			builder.put(grammarAccess.getServiceAccess().getRestartAssignment_3_5_1(), "rule__Service__RestartAssignment_3_5_1");
			builder.put(grammarAccess.getServiceAccess().getInitAssignment_3_6_1(), "rule__Service__InitAssignment_3_6_1");
			builder.put(grammarAccess.getServiceAccess().getRead_onlyAssignment_3_7_1(), "rule__Service__Read_onlyAssignment_3_7_1");
			builder.put(grammarAccess.getServiceAccess().getLinksAssignment_3_8_1_1(), "rule__Service__LinksAssignment_3_8_1_1");
			builder.put(grammarAccess.getServiceAccess().getDepends_onAssignment_3_9_1(), "rule__Service__Depends_onAssignment_3_9_1");
			builder.put(grammarAccess.getServiceAccess().getNetworksAssignment_3_10_1_0(), "rule__Service__NetworksAssignment_3_10_1_0");
			builder.put(grammarAccess.getServiceAccess().getNetworksAssignment_3_10_1_1(), "rule__Service__NetworksAssignment_3_10_1_1");
			builder.put(grammarAccess.getServiceAccess().getVolumesAssignment_3_11_1_1(), "rule__Service__VolumesAssignment_3_11_1_1");
			builder.put(grammarAccess.getServiceAccess().getConfigsAssignment_3_12_1_1(), "rule__Service__ConfigsAssignment_3_12_1_1");
			builder.put(grammarAccess.getServiceAccess().getSecretsAssignment_3_13_1_1(), "rule__Service__SecretsAssignment_3_13_1_1");
			builder.put(grammarAccess.getServiceAccess().getEnvironmentAssignment_3_14_1_0(), "rule__Service__EnvironmentAssignment_3_14_1_0");
			builder.put(grammarAccess.getServiceAccess().getEnvironmentAssignment_3_14_1_1(), "rule__Service__EnvironmentAssignment_3_14_1_1");
			builder.put(grammarAccess.getServiceAccess().getDevicesAssignment_3_15_1_1(), "rule__Service__DevicesAssignment_3_15_1_1");
			builder.put(grammarAccess.getServiceAccess().getDnsAssignment_3_16_1_0_1(), "rule__Service__DnsAssignment_3_16_1_0_1");
			builder.put(grammarAccess.getServiceAccess().getDnsAssignment_3_16_1_1(), "rule__Service__DnsAssignment_3_16_1_1");
			builder.put(grammarAccess.getServiceAccess().getPortsAssignment_3_17_1_1(), "rule__Service__PortsAssignment_3_17_1_1");
			builder.put(grammarAccess.getEnvironmentVariableMapAccess().getNameAssignment_1(), "rule__EnvironmentVariableMap__NameAssignment_1");
			builder.put(grammarAccess.getEnvironmentVariableMapAccess().getValueAssignment_3_0(), "rule__EnvironmentVariableMap__ValueAssignment_3_0");
			builder.put(grammarAccess.getEnvironmentVariableMapAccess().getValueAssignment_3_1(), "rule__EnvironmentVariableMap__ValueAssignment_3_1");
			builder.put(grammarAccess.getEnvironmentVariableListAccess().getNameAssignment_2(), "rule__EnvironmentVariableList__NameAssignment_2");
			builder.put(grammarAccess.getEnvironmentVariableListAccess().getValueAssignment_3_1_0(), "rule__EnvironmentVariableList__ValueAssignment_3_1_0");
			builder.put(grammarAccess.getEnvironmentVariableListAccess().getValueAssignment_3_1_1(), "rule__EnvironmentVariableList__ValueAssignment_3_1_1");
			builder.put(grammarAccess.getPortAccess().getValueAssignment_1(), "rule__Port__ValueAssignment_1");
			builder.put(grammarAccess.getDeviceAccess().getValueAssignment_1(), "rule__Device__ValueAssignment_1");
			builder.put(grammarAccess.getLinkAccess().getServiceAssignment_1(), "rule__Link__ServiceAssignment_1");
			builder.put(grammarAccess.getLinkAccess().getAliasAssignment_2_1(), "rule__Link__AliasAssignment_2_1");
			builder.put(grammarAccess.getDependencyAccess().getServiceAssignment_1_0_1(), "rule__Dependency__ServiceAssignment_1_0_1");
			builder.put(grammarAccess.getDependencyAccess().getServiceAssignment_1_1_0(), "rule__Dependency__ServiceAssignment_1_1_0");
			builder.put(grammarAccess.getDependencyAccess().getConditionAssignment_1_1_3(), "rule__Dependency__ConditionAssignment_1_1_3");
			builder.put(grammarAccess.getNetworkConnector_longAccess().getNetworkAssignment_1(), "rule__NetworkConnector_long__NetworkAssignment_1");
			builder.put(grammarAccess.getNetworkConnector_longAccess().getIpv4_addressAssignment_3_0_1(), "rule__NetworkConnector_long__Ipv4_addressAssignment_3_0_1");
			builder.put(grammarAccess.getNetworkConnector_longAccess().getPriorityAssignment_3_1_1(), "rule__NetworkConnector_long__PriorityAssignment_3_1_1");
			builder.put(grammarAccess.getNetworkConnector_longAccess().getAliasesAssignment_3_2_1_1(), "rule__NetworkConnector_long__AliasesAssignment_3_2_1_1");
			builder.put(grammarAccess.getNetworkConnector_longAccess().getLink_local_ipsAssignment_3_3_1_1(), "rule__NetworkConnector_long__Link_local_ipsAssignment_3_3_1_1");
			builder.put(grammarAccess.getNetworkConnector_shortAccess().getNetworkAssignment_2(), "rule__NetworkConnector_short__NetworkAssignment_2");
			builder.put(grammarAccess.getAliasAccess().getAliasAssignment_1(), "rule__Alias__AliasAssignment_1");
			builder.put(grammarAccess.getVolumeConnectorAccess().getVolumeAssignment_1_0_0(), "rule__VolumeConnector__VolumeAssignment_1_0_0");
			builder.put(grammarAccess.getVolumeConnectorAccess().getContainer_pathAssignment_1_0_2(), "rule__VolumeConnector__Container_pathAssignment_1_0_2");
			builder.put(grammarAccess.getVolumeConnectorAccess().getAccess_modeAssignment_1_0_3_1(), "rule__VolumeConnector__Access_modeAssignment_1_0_3_1");
			builder.put(grammarAccess.getVolumeConnectorAccess().getVolumeAssignment_1_1_0_1(), "rule__VolumeConnector__VolumeAssignment_1_1_0_1");
			builder.put(grammarAccess.getVolumeConnectorAccess().getTypeAssignment_1_1_1_1(), "rule__VolumeConnector__TypeAssignment_1_1_1_1");
			builder.put(grammarAccess.getVolumeConnectorAccess().getContainer_pathAssignment_1_1_2_1(), "rule__VolumeConnector__Container_pathAssignment_1_1_2_1");
			builder.put(grammarAccess.getVolumeConnectorAccess().getRead_onlyAssignment_1_1_3_1(), "rule__VolumeConnector__Read_onlyAssignment_1_1_3_1");
			builder.put(grammarAccess.getVolumeConnectorAccess().getPropagationAssignment_1_1_4_2(), "rule__VolumeConnector__PropagationAssignment_1_1_4_2");
			builder.put(grammarAccess.getVolumeConnectorAccess().getNocopyAssignment_1_1_5_2(), "rule__VolumeConnector__NocopyAssignment_1_1_5_2");
			builder.put(grammarAccess.getVolumeConnectorAccess().getSizeAssignment_1_1_6_3(), "rule__VolumeConnector__SizeAssignment_1_1_6_3");
			builder.put(grammarAccess.getConfigConnectorAccess().getConfigAssignment_1_0(), "rule__ConfigConnector__ConfigAssignment_1_0");
			builder.put(grammarAccess.getConfigConnectorAccess().getConfigAssignment_1_1_0_1(), "rule__ConfigConnector__ConfigAssignment_1_1_0_1");
			builder.put(grammarAccess.getConfigConnectorAccess().getTargetAssignment_1_1_1_1(), "rule__ConfigConnector__TargetAssignment_1_1_1_1");
			builder.put(grammarAccess.getConfigConnectorAccess().getUidAssignment_1_1_2_1(), "rule__ConfigConnector__UidAssignment_1_1_2_1");
			builder.put(grammarAccess.getConfigConnectorAccess().getGidAssignment_1_1_3_1(), "rule__ConfigConnector__GidAssignment_1_1_3_1");
			builder.put(grammarAccess.getConfigConnectorAccess().getModeAssignment_1_1_4_1(), "rule__ConfigConnector__ModeAssignment_1_1_4_1");
			builder.put(grammarAccess.getSecretConnectorAccess().getSecretAssignment_1_0(), "rule__SecretConnector__SecretAssignment_1_0");
			builder.put(grammarAccess.getSecretConnectorAccess().getSecretAssignment_1_1_0_1(), "rule__SecretConnector__SecretAssignment_1_1_0_1");
			builder.put(grammarAccess.getSecretConnectorAccess().getTargetAssignment_1_1_1_1(), "rule__SecretConnector__TargetAssignment_1_1_1_1");
			builder.put(grammarAccess.getSecretConnectorAccess().getUidAssignment_1_1_2_1(), "rule__SecretConnector__UidAssignment_1_1_2_1");
			builder.put(grammarAccess.getSecretConnectorAccess().getGidAssignment_1_1_3_1(), "rule__SecretConnector__GidAssignment_1_1_3_1");
			builder.put(grammarAccess.getSecretConnectorAccess().getModeAssignment_1_1_4_1(), "rule__SecretConnector__ModeAssignment_1_1_4_1");
			builder.put(grammarAccess.getNetworkAccess().getNameAssignment_1(), "rule__Network__NameAssignment_1");
			builder.put(grammarAccess.getNetworkAccess().getDriverAssignment_3_1_0_1(), "rule__Network__DriverAssignment_3_1_0_1");
			builder.put(grammarAccess.getNetworkAccess().getAttachableAssignment_3_1_1_1(), "rule__Network__AttachableAssignment_3_1_1_1");
			builder.put(grammarAccess.getNetworkAccess().getEnable_ipv6Assignment_3_1_2_1(), "rule__Network__Enable_ipv6Assignment_3_1_2_1");
			builder.put(grammarAccess.getNetworkAccess().getInternalAssignment_3_1_3_1(), "rule__Network__InternalAssignment_3_1_3_1");
			builder.put(grammarAccess.getNetworkAccess().getExternalAssignment_3_1_4_1(), "rule__Network__ExternalAssignment_3_1_4_1");
			builder.put(grammarAccess.getNetworkAccess().getNetwork_nameAssignment_3_1_5_1(), "rule__Network__Network_nameAssignment_3_1_5_1");
			builder.put(grammarAccess.getNetworkAccess().getLabelsAssignment_3_1_6_1(), "rule__Network__LabelsAssignment_3_1_6_1");
			builder.put(grammarAccess.getNetworkAccess().getDriver_optsAssignment_3_1_7_1(), "rule__Network__Driver_optsAssignment_3_1_7_1");
			builder.put(grammarAccess.getNetworkAccess().getIpamAssignment_3_1_8_1(), "rule__Network__IpamAssignment_3_1_8_1");
			builder.put(grammarAccess.getVolumeAccess().getNameAssignment_1(), "rule__Volume__NameAssignment_1");
			builder.put(grammarAccess.getVolumeAccess().getExternalAssignment_3_0_1(), "rule__Volume__ExternalAssignment_3_0_1");
			builder.put(grammarAccess.getVolumeAccess().getDriverAssignment_3_1_1(), "rule__Volume__DriverAssignment_3_1_1");
			builder.put(grammarAccess.getVolumeAccess().getVolume_nameAssignment_3_2_1(), "rule__Volume__Volume_nameAssignment_3_2_1");
			builder.put(grammarAccess.getVolumeAccess().getLabelsAssignment_3_3_1(), "rule__Volume__LabelsAssignment_3_3_1");
			builder.put(grammarAccess.getVolumeAccess().getDriver_optsAssignment_3_4_1(), "rule__Volume__Driver_optsAssignment_3_4_1");
			builder.put(grammarAccess.getConfigAccess().getNameAssignment_1(), "rule__Config__NameAssignment_1");
			builder.put(grammarAccess.getConfigAccess().getExternalAssignment_3_0_1(), "rule__Config__ExternalAssignment_3_0_1");
			builder.put(grammarAccess.getConfigAccess().getFileAssignment_3_1_1(), "rule__Config__FileAssignment_3_1_1");
			builder.put(grammarAccess.getConfigAccess().getConfig_nameAssignment_3_2_1(), "rule__Config__Config_nameAssignment_3_2_1");
			builder.put(grammarAccess.getSecretAccess().getNameAssignment_1(), "rule__Secret__NameAssignment_1");
			builder.put(grammarAccess.getSecretAccess().getExternalAssignment_3_0_1(), "rule__Secret__ExternalAssignment_3_0_1");
			builder.put(grammarAccess.getSecretAccess().getFileAssignment_3_1_1(), "rule__Secret__FileAssignment_3_1_1");
			builder.put(grammarAccess.getSecretAccess().getEnvironmentAssignment_3_2_1(), "rule__Secret__EnvironmentAssignment_3_2_1");
			builder.put(grammarAccess.getSecretAccess().getSecret_nameAssignment_3_3_1(), "rule__Secret__Secret_nameAssignment_3_3_1");
			builder.put(grammarAccess.getVolumeLabelAccess().getNameAssignment_1(), "rule__VolumeLabel__NameAssignment_1");
			builder.put(grammarAccess.getVolumeLabelAccess().getValueAssignment_3(), "rule__VolumeLabel__ValueAssignment_3");
			builder.put(grammarAccess.getVolumeDriverOptAccess().getNameAssignment_1(), "rule__VolumeDriverOpt__NameAssignment_1");
			builder.put(grammarAccess.getVolumeDriverOptAccess().getValueAssignment_3(), "rule__VolumeDriverOpt__ValueAssignment_3");
			builder.put(grammarAccess.getNetworkLabelAccess().getNameAssignment_1(), "rule__NetworkLabel__NameAssignment_1");
			builder.put(grammarAccess.getNetworkLabelAccess().getValueAssignment_3(), "rule__NetworkLabel__ValueAssignment_3");
			builder.put(grammarAccess.getNetworkDriverOptAccess().getNameAssignment_1(), "rule__NetworkDriverOpt__NameAssignment_1");
			builder.put(grammarAccess.getNetworkDriverOptAccess().getValueAssignment_3(), "rule__NetworkDriverOpt__ValueAssignment_3");
			builder.put(grammarAccess.getIPAMAccess().getDriverAssignment_1_0_1(), "rule__IPAM__DriverAssignment_1_0_1");
			builder.put(grammarAccess.getIPAMAccess().getConfigsAssignment_1_1_1_1(), "rule__IPAM__ConfigsAssignment_1_1_1_1");
			builder.put(grammarAccess.getIPAMAccess().getOptionsAssignment_1_2_1(), "rule__IPAM__OptionsAssignment_1_2_1");
			builder.put(grammarAccess.getIPAMConfigAccess().getSubnetAssignment_1_0_1(), "rule__IPAMConfig__SubnetAssignment_1_0_1");
			builder.put(grammarAccess.getIPAMConfigAccess().getIp_rangeAssignment_1_1_1(), "rule__IPAMConfig__Ip_rangeAssignment_1_1_1");
			builder.put(grammarAccess.getIPAMConfigAccess().getGatewayAssignment_1_2_1(), "rule__IPAMConfig__GatewayAssignment_1_2_1");
			builder.put(grammarAccess.getIPAMConfigAccess().getAux_addressesAssignment_1_3_1(), "rule__IPAMConfig__Aux_addressesAssignment_1_3_1");
			builder.put(grammarAccess.getIPAMOptionAccess().getNameAssignment_1(), "rule__IPAMOption__NameAssignment_1");
			builder.put(grammarAccess.getIPAMOptionAccess().getValueAssignment_3(), "rule__IPAMOption__ValueAssignment_3");
			builder.put(grammarAccess.getIPAMAddressAccess().getNameAssignment_1(), "rule__IPAMAddress__NameAssignment_1");
			builder.put(grammarAccess.getIPAMAddressAccess().getDnsAssignment_3(), "rule__IPAMAddress__DnsAssignment_3");
			builder.put(grammarAccess.getDNSAccess().getDns1Assignment_0(), "rule__DNS__Dns1Assignment_0");
			builder.put(grammarAccess.getDNSAccess().getDns2Assignment_2(), "rule__DNS__Dns2Assignment_2");
			builder.put(grammarAccess.getDNSAccess().getDns3Assignment_4(), "rule__DNS__Dns3Assignment_4");
			builder.put(grammarAccess.getDNSAccess().getDns4Assignment_6(), "rule__DNS__Dns4Assignment_6");
			builder.put(grammarAccess.getNetworkAddressAccess().getDns1Assignment_0(), "rule__NetworkAddress__Dns1Assignment_0");
			builder.put(grammarAccess.getNetworkAddressAccess().getDns2Assignment_2(), "rule__NetworkAddress__Dns2Assignment_2");
			builder.put(grammarAccess.getNetworkAddressAccess().getDns3Assignment_4(), "rule__NetworkAddress__Dns3Assignment_4");
			builder.put(grammarAccess.getNetworkAddressAccess().getDns4Assignment_6(), "rule__NetworkAddress__Dns4Assignment_6");
			builder.put(grammarAccess.getNetworkAddressAccess().getNetIdAssignment_8(), "rule__NetworkAddress__NetIdAssignment_8");
			builder.put(grammarAccess.getDockerComposeAccess().getUnorderedGroup(), "rule__DockerCompose__UnorderedGroup");
			builder.put(grammarAccess.getServiceAccess().getUnorderedGroup_3(), "rule__Service__UnorderedGroup_3");
			builder.put(grammarAccess.getNetworkConnector_longAccess().getUnorderedGroup_3(), "rule__NetworkConnector_long__UnorderedGroup_3");
			builder.put(grammarAccess.getVolumeConnectorAccess().getUnorderedGroup_1_1(), "rule__VolumeConnector__UnorderedGroup_1_1");
			builder.put(grammarAccess.getConfigConnectorAccess().getUnorderedGroup_1_1(), "rule__ConfigConnector__UnorderedGroup_1_1");
			builder.put(grammarAccess.getSecretConnectorAccess().getUnorderedGroup_1_1(), "rule__SecretConnector__UnorderedGroup_1_1");
			builder.put(grammarAccess.getNetworkAccess().getUnorderedGroup_3_1(), "rule__Network__UnorderedGroup_3_1");
			builder.put(grammarAccess.getVolumeAccess().getUnorderedGroup_3(), "rule__Volume__UnorderedGroup_3");
			builder.put(grammarAccess.getConfigAccess().getUnorderedGroup_3(), "rule__Config__UnorderedGroup_3");
			builder.put(grammarAccess.getSecretAccess().getUnorderedGroup_3(), "rule__Secret__UnorderedGroup_3");
			builder.put(grammarAccess.getIPAMAccess().getUnorderedGroup_1(), "rule__IPAM__UnorderedGroup_1");
			builder.put(grammarAccess.getIPAMConfigAccess().getUnorderedGroup_1(), "rule__IPAMConfig__UnorderedGroup_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private DockerComposeGrammarAccess grammarAccess;

	@Override
	protected InternalDockerComposeParser createParser() {
		InternalDockerComposeParser result = new InternalDockerComposeParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DockerComposeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DockerComposeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
