/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.dockercompose;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DockerComposeStandaloneSetup extends DockerComposeStandaloneSetupGenerated {

	public static void doSetup() {
		new DockerComposeStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
