/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.dockercompose.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDockerComposeScopeProvider extends DelegatingScopeProvider {
}
