/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.dockercompose.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.dockercompose.ui.internal.DockercomposeActivator;

public class DockerComposeUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DockercomposeActivator.getInstance().getInjector("org.xtext.example.dockercompose.DockerCompose");
	}

}
