/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.dockercompose.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.dockercompose.DockerComposeRuntimeModule;
import org.xtext.example.dockercompose.DockerComposeStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DockerComposeIdeSetup extends DockerComposeStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DockerComposeRuntimeModule(), new DockerComposeIdeModule()));
	}
	
}
