/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.dockercompose.ide;


/**
 * Use this class to register ide components.
 */
public class DockerComposeIdeModule extends AbstractDockerComposeIdeModule {
}
