/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.dockercompose.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class DockerComposeUiModule extends AbstractDockerComposeUiModule {

	public DockerComposeUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
