/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.dockercompose.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DockerComposeAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/dockercompose/parser/antlr/internal/InternalDockerCompose.tokens");
	}
}
