/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.dockercompose.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.dockercompose.parser.antlr.internal.InternalDockerComposeParser;
import org.xtext.example.dockercompose.services.DockerComposeGrammarAccess;

public class DockerComposeParser extends AbstractAntlrParser {

	@Inject
	private DockerComposeGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDockerComposeParser createParser(XtextTokenStream stream) {
		return new InternalDockerComposeParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "DockerCompose";
	}

	public DockerComposeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DockerComposeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
